// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJPjoPHV4ZIeXeeyHA3fq3uaV-HpKMcxI',
    appId: '1:728474682739:web:ed670e536a0f87d1d67106',
    messagingSenderId: '728474682739',
    projectId: 'education-appp',
    authDomain: 'education-appp.firebaseapp.com',
    storageBucket: 'education-appp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwTnt2LS9X0CDIkK3CU4dfWtJJ7kWybjE',
    appId: '1:728474682739:android:fde97d8ac1bf034dd67106',
    messagingSenderId: '728474682739',
    projectId: 'education-appp',
    storageBucket: 'education-appp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDug29js-ux9QHoMPMNh9AUPhRCdDuiJU8',
    appId: '1:728474682739:ios:20f6d9a25fbb9ed6d67106',
    messagingSenderId: '728474682739',
    projectId: 'education-appp',
    storageBucket: 'education-appp.appspot.com',
    iosBundleId: 'com.example.educationApp',
  );
}
